[tox]
requires = tox>=4.28
env_list =
    py310-lowest-core
    py310-latest
    py311-latest
    py312-latest
    py313-latest
    py314-latest
    py310-sklearn-1.3
    py310-sklearn-1.4
    py310-sklearn-1.5
    py310-sklearn-1.6
    py310-sklearn-1.7
    py311-sklearn-1.8
    py311-sklearn-1.9
    py310-lowest-boosted
    py310-latest-boosted
    py311-latest-boosted
    py312-latest-boosted
    py313-latest-boosted

[testenv]
package = editable
extras = test
commands =
    pytest -ra --tb=short --durations=20 {posargs}

[testenv:py310-lowest-core]
base_python = python3.10
constraints = constraints/lowest-core.txt

[testenv:py310-latest]
base_python = python3.10

[testenv:py311-latest]
base_python = python3.11

[testenv:py312-latest]
base_python = python3.12

[testenv:py313-latest]
base_python = python3.13

[testenv:py314-latest]
base_python = python3.14

[testenv:py310-sklearn-1.3]
base_python = python3.10
constraints = constraints/sklearn-1.3.txt

[testenv:py310-sklearn-1.4]
base_python = python3.10
constraints = constraints/sklearn-1.4.txt

[testenv:py310-sklearn-1.5]
base_python = python3.10
constraints = constraints/sklearn-1.5.txt

[testenv:py310-sklearn-1.6]
base_python = python3.10
constraints = constraints/sklearn-1.6.txt

[testenv:py310-sklearn-1.7]
base_python = python3.10
constraints = constraints/sklearn-1.7.txt

[testenv:py311-sklearn-1.8]
base_python = python3.11
constraints = constraints/sklearn-1.8.txt

[testenv:py311-sklearn-1.9]
base_python = python3.11
constraints = constraints/sklearn-1.9.txt

[testenv:py310-lowest-boosted]
base_python = python3.10
extras =
    test
    boosted
constraints = constraints/lowest-boosted.txt

[testenv:py310-latest-boosted]
base_python = python3.10
extras =
    test
    boosted

[testenv:py311-latest-boosted]
base_python = python3.11
extras =
    test
    boosted

[testenv:py312-latest-boosted]
base_python = python3.12
extras =
    test
    boosted

[testenv:py313-latest-boosted]
base_python = python3.13
extras =
    test
    boosted
